config/routes.rb
OfficeClassifieds::Application.routes.draw do
  devise_for :brokers 

  resources :brokers do 
    resources :favorites, only: [:index]
    get 'brokers_listings', to: 'office_listings#brokers_listings', :as => 'brokers_listings'
  end

  devise_for :renters, :controllers => { :registrations => "authentication/registrations" } 

  resources :renters do 
    resources :favorites, only: [:index, :new, :create, :destroy]
    resources :appointments, only: [:index, :create, :destroy]
  end

  match 'renters/:renter_id/preference_lists/configure_preference_list', to: 'preference_lists#configure_preference_list', via: :get, as: 'preference_list_configure'
  match 'renters/:renter_id/preference_lists/add_neighborhood', to: 'preference_lists#add_neighborhood', via: :patch, as: 'preference_list_add_neighborhood'
  match 'renters/:renter_id/preference_lists/remove_neighborhood/:neighborhood_id', to: 'preference_lists#remove_neighborhood', via: :patch, as: 'preference_list_remove_neighborhood'
  match 'renters/:renter_id/preference_lists/add_broker', to: 'preference_lists#add_broker', via: :patch, as: 'preference_list_add_broker'
  match 'renters/:renter_id/preference_lists/remove_broker/:broker_id', to: 'preference_lists#remove_broker', via: :patch, as: 'preference_list_remove_broker'
  match 'renters/:renter_id/preference_lists/add_amenity', to: 'preference_lists#add_amenity', via: :patch, as: 'preference_list_add_amenity'
  match 'renters/:renter_id/preference_lists/remove_amenity/:amenity', to: 'preference_lists#remove_amenity', via: :patch, as: 'preference_list_remove_amenity'
  match 'renters/:renter_id/preference_lists/:id/delete', to: 'preference_lists#destroy', via: :delete, as: 'preference_list_delete'
  match 'renters/:renter_id/preference_lists/create', to: 'preference_lists#create', via: :post, as: 'preference_list_create'

  root :to => "home#index"

  # Neighborhoods Paths
  resources :cities, only: [:show] do
    resources :neighborhoods, only: [:index, :show]
  end

  resources :neighborhoods do
    collection do
      get 'add_listing', to: 'neighborhoods#add_listing', :as => 'neighborhood_add_listing'
    end
  end

  # Office Listings Paths
  resources :neighborhoods, only: [:show] do
    resources :office_listings, only: [:index, :show, :new, :create, :edit]
  end

  # Viewings Paths
  resources :office_listings, only: [:show] do 
    resources :viewings, only: [:new, :create, :destroy, :index]
  end
  resources :images, only: [:create]

  # Notifications Paths
  resources :notifications, only: [:update]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index 
	
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
		
<script src="stellar.js"></script>
<script>
$(function(){
	$.stellar({
		horizontalScrolling: false,
		verticalOffset: 40
	});
});
</script>

<div class="photo new_york" data-stellar-background-ratio="0"><span class="city_names"></span></div>
<div class="photo diff-space" data-stellar-background-ratio="2">
  <a href="<%= city_neighborhoods_path(city_id: City.find_by_name("New York")) %>"><div class="small button browse">Browse office spaces</div></a> submitted by <span class="special">registered brokers</span>.
</div>	
<div class="photo singapore" data-stellar-background-ratio="0"><span class="city_names"></span></div>
<div class="photo diff-space" data-stellar-background-ratio="2">
  <a href="<%= current_renter ? renter_favorites_path(renter_id: current_renter.id) : new_renter_registration_path %>"><div class= "small button favorites">Add Listings to Favorites</div></a> to browse at<span class="special3"> your convenience</span>.
</div>
<div class="photo sf" data-stellar-background-ratio="0">
	<span class="city_names"></span>
</div>
<div class="photo diff-space-change" data-stellar-background-ratio="2">
  Build a <span class="special2">visual, browseable itinerary</span> of <span class="special3">viewings</span> scheduled <span class="special">by brokers</span>.	
	<br>
	<% if current_renter || current_broker %>
		<a class="button small radius browse-offices" href="<%= neighborhoods_path(city_id: City.find_by_name('New York').id) %>"> Browse our selection</a>
	<% end %>
	<% unless current_renter || current_broker %>	
    <br>
		<a class="signup-div button small final-signup" href="#">Sign Up Today</a>
	<% end %>
	<br>
	<a class="small button signup" data-reveal-id="renter_sign_up" href=<%= new_renter_registration_path%>>Renter Sign Up</a>
	<a class="small button signup" data-reveal-id="broker_sign_up" href=<%= new_broker_registration_path%>>Broker Sign Up</a>
</div>	
<div class="photo hk" data-stellar-background-ratio="0"><span class="city_names"></span></div>
<div class="photo diff-space-final" data-stellar-background-ratio="0"><span>Find the <span class = 'special'> perfect </span> <span class = 'special2'> space </span> for your <span class = 'special3'> business. </span></span></div>