config/routes.rb
OfficeClassifieds::Application.routes.draw do
  devise_for :brokers 

  resources :brokers do 
    resources :favorites, only: [:index]
    get 'brokers_listings', to: 'office_listings#brokers_listings', :as => 'brokers_listings'
  end

  devise_for :renters, :controllers => { :registrations => "authentication/registrations" } 

  resources :renters do 
    resources :favorites, only: [:index, :new, :create, :destroy]
    resources :appointments, only: [:index, :create, :destroy]
  end

  match 'renters/:renter_id/preference_lists/configure_preference_list', to: 'preference_lists#configure_preference_list', via: :get, as: 'preference_list_configure'
  match 'renters/:renter_id/preference_lists/add_neighborhood', to: 'preference_lists#add_neighborhood', via: :patch, as: 'preference_list_add_neighborhood'
  match 'renters/:renter_id/preference_lists/remove_neighborhood/:neighborhood_id', to: 'preference_lists#remove_neighborhood', via: :patch, as: 'preference_list_remove_neighborhood'
  match 'renters/:renter_id/preference_lists/add_broker', to: 'preference_lists#add_broker', via: :patch, as: 'preference_list_add_broker'
  match 'renters/:renter_id/preference_lists/remove_broker/:broker_id', to: 'preference_lists#remove_broker', via: :patch, as: 'preference_list_remove_broker'
  match 'renters/:renter_id/preference_lists/add_amenity', to: 'preference_lists#add_amenity', via: :patch, as: 'preference_list_add_amenity'
  match 'renters/:renter_id/preference_lists/remove_amenity/:amenity', to: 'preference_lists#remove_amenity', via: :patch, as: 'preference_list_remove_amenity'
  match 'renters/:renter_id/preference_lists/:id/delete', to: 'preference_lists#destroy', via: :delete, as: 'preference_list_delete'
  match 'renters/:renter_id/preference_lists/create', to: 'preference_lists#create', via: :post, as: 'preference_list_create'

  root :to => "home#index"

  # Neighborhoods Paths
  resources :cities, only: [:show] do
    resources :neighborhoods, only: [:index, :show]
  end

  resources :neighborhoods do
    collection do
      get 'add_listing', to: 'neighborhoods#add_listing', :as => 'neighborhood_add_listing'
    end
  end

  # Office Listings Paths
  resources :neighborhoods, only: [:show] do
    resources :office_listings, only: [:index, :show, :new, :create, :edit]
  end

  # Viewings Paths
  resources :office_listings, only: [:show] do 
    resources :viewings, only: [:new, :create, :destroy, :index]
  end
  resources :images, only: [:create]

  # Notifications Paths
  resources :notifications, only: [:update]
end

app/models/neighborhood.rb
# == Schema Information
#
# Table name: neighborhoods
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  city_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  img_url    :string(255)
#  latitude   :float
#  longitude  :float
#  address    :text
#

class Neighborhood < ActiveRecord::Base
  attr_accessible :city_id, :img_url, :name, :address, :latitude, :longitude
  validates :name, presence: true, length: { in: 3..50 }

  belongs_to :city
  has_many :office_listings
  has_and_belongs_to_many :preference_lists

  geocoded_by :address 
  before_save :geocode
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  def index
    @neighborhoods = Neighborhood.find_all_by_city_id(params[:city_id])
    @city = City.find(params[:city_id])
    @city_name = @city.name
  end

  def show
  end

  def add_listing
  	@neighborhoods = Neighborhood.all
    @city = City.find_by_name('New York') # get rid of this diabolical hardcoded bullshit ASAP
  end
end

app/helpers/neighborhood_helper.rb
module NeighborhoodHelper
end

app/views/neighborhoods/add_listing.html.haml
.add-listing-heading
	%h1.add-listing-label Which neighborhood will this office be located in?
.row.neighborhoods-page-add-listing
	-@neighborhoods.each do |neighborhood|
		=link_to new_neighborhood_office_listing_path(neighborhood_id: neighborhood.id), id: neighborhood.name do
			.large-4.small-6.columns.neighborhood-box{:style => "background-image: url(#{image_path "#{neighborhood.img_url}"})"}
				=neighborhood.name	

app/views/neighborhoods/index.html.haml
-if !@neighborhoods.empty?
  %h1 Neighborhoods
  .row.neighborhoods-page
    -@neighborhoods.each do |neighborhood|
      =link_to neighborhood_office_listings_path(neighborhood_id: neighborhood.id), id: neighborhood.name do
        .large-4.small-6.columns.neighborhood-box{:style => "background-image: url(#{image_path "#{neighborhood.img_url}"})"}
          =neighborhood.name	
-elsif @city_name == "Singapore"
  .row.coming-soon
    = image_tag "singapore_3.gif", class: 'singapore-coming-soon'
-elsif @city_name == "Jakarta"
  .row.coming-soon
    = image_tag "singapore_3.gif", class: 'singapore-coming-soon'
-elsif @city_name == "Hong Kong"
  .row.coming-soon
    = image_tag "singapore_3.gif", class: 'singapore-coming-soon'
-elsif @city_name == "Reno"
  .row.coming-soon
    = image_tag "singapore_3.gif", class: 'singapore-coming-soon'