config/routes.rb
OfficeClassifieds::Application.routes.draw do
  devise_for :brokers 

  resources :brokers do 
    resources :favorites, only: [:index]
    get 'brokers_listings', to: 'office_listings#brokers_listings', :as => 'brokers_listings'
  end

  devise_for :renters, :controllers => { :registrations => "authentication/registrations" } 

  resources :renters do 
    resources :favorites, only: [:index, :new, :create, :destroy]
    resources :appointments, only: [:index, :create, :destroy]
  end

  match 'renters/:renter_id/preference_lists/configure_preference_list', to: 'preference_lists#configure_preference_list', via: :get, as: 'preference_list_configure'
  match 'renters/:renter_id/preference_lists/add_neighborhood', to: 'preference_lists#add_neighborhood', via: :patch, as: 'preference_list_add_neighborhood'
  match 'renters/:renter_id/preference_lists/remove_neighborhood/:neighborhood_id', to: 'preference_lists#remove_neighborhood', via: :patch, as: 'preference_list_remove_neighborhood'
  match 'renters/:renter_id/preference_lists/add_broker', to: 'preference_lists#add_broker', via: :patch, as: 'preference_list_add_broker'
  match 'renters/:renter_id/preference_lists/remove_broker/:broker_id', to: 'preference_lists#remove_broker', via: :patch, as: 'preference_list_remove_broker'
  match 'renters/:renter_id/preference_lists/add_amenity', to: 'preference_lists#add_amenity', via: :patch, as: 'preference_list_add_amenity'
  match 'renters/:renter_id/preference_lists/remove_amenity/:amenity', to: 'preference_lists#remove_amenity', via: :patch, as: 'preference_list_remove_amenity'
  match 'renters/:renter_id/preference_lists/:id/delete', to: 'preference_lists#destroy', via: :delete, as: 'preference_list_delete'
  match 'renters/:renter_id/preference_lists/create', to: 'preference_lists#create', via: :post, as: 'preference_list_create'

  root :to => "home#index"

  # Neighborhoods Paths
  resources :cities, only: [:show] do
    resources :neighborhoods, only: [:index, :show]
  end

  resources :neighborhoods do
    collection do
      get 'add_listing', to: 'neighborhoods#add_listing', :as => 'neighborhood_add_listing'
    end
  end

  # Office Listings Paths
  resources :neighborhoods, only: [:show] do
    resources :office_listings, only: [:index, :show, :new, :create, :edit]
  end

  # Viewings Paths
  resources :office_listings, only: [:show] do 
    resources :viewings, only: [:new, :create, :destroy, :index]
  end
  resources :images, only: [:create]

  # Notifications Paths
  resources :notifications, only: [:update]
end

app/models/preference_list.rb
# == Schema Information
#
# Table name: preference_lists
#
#  id           :integer          not null, primary key
#  renter_id    :integer
#  min_price    :integer
#  max_price    :integer
#  min_sq_feet  :integer
#  max_sq_feet  :integer
#  kitchen      :boolean
#  reception    :boolean
#  light        :boolean
#  shower       :boolean
#  high_ceiling :boolean
#  move_in      :boolean
#  patio        :boolean
#  furniture    :boolean
#  created_at   :datetime
#  updated_at   :datetime
#  email        :boolean
#

class PreferenceList < ActiveRecord::Base
  attr_accessible :neighborhoods, :renter_id, :id, :min_price, :max_price, :min_square_feet, :max_square_feet, :kitchen, :reception, :patio, :furniture, :lighting, :high_ceiling, :shower, :move_in, :email
  has_and_belongs_to_many :neighborhoods
  has_and_belongs_to_many :brokers
  belongs_to :renter
end

app/controllers/preference_lists_controller.rb
class PreferenceListsController < ApplicationController
  before_filter :create_preference_list

  def configure_preference_list
    @all_neighborhoods = Neighborhood.all
    @all_brokers = Broker.all
    @renter_neighborhoods = current_renter.preference_list.neighborhoods || []
    @renter_brokers = current_renter.preference_list.brokers || []
    @renter_amenities = get_selected_amenities(current_renter.preference_list)
    @all_amenities = ['Reception', 'Light', 'Shower', 'Move_in', 'High_ceiling', 'Patio', 'Furniture']
    render :edit
  end


  def add_neighborhood
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
    preference_list = current_renter.preference_list
    if preference_list.neighborhoods.include? @neighborhood
      @neighborhood = ""
    else
      preference_list.neighborhoods << @neighborhood
      preference_list.activated = true if !preference_list.activated
      preference_list.save
      current_renter.save
    end
    respond_to do |format|
      format.js
    end
  end

  def remove_neighborhood
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
    preference_list = current_renter.preference_list
    preference_list.neighborhoods.delete(@neighborhood)
    preference_list.save
    respond_to do |format|
      format.js
    end
  end

  def add_broker
    @broker = Broker.find(params[:broker_id])
    preference_list = current_renter.preference_list 
    if preference_list.brokers.include? @broker
      @broker = ""
    else
      preference_list.brokers << @broker
      preference_list.activated = true if !preference_list.activated
      preference_list.save
    end
    respond_to do |format|
      format.js
    end
  end

  def remove_broker
    @broker = Broker.find(params[:broker_id])
    preference_list = current_renter.preference_list
    preference_list.brokers.delete(@broker)
    preference_list.save
    respond_to do |format|
      format.js
    end
  end

  def add_amenity
    @amenity = params[:amenity]
    preference_list = current_renter.preference_list
    if !preference_list[@amenity.downcase]
      preference_list[@amenity.downcase] =  true
    else
      @amenity = ""
    end
    preference_list.save
    respond_to do |format|
      format.js
    end
  end

  def remove_amenity
    @amenity = params[:amenity]
    preference_list = current_renter.preference_list
    preference_list[@amenity.downcase] = false
    preference_list.save
    respond_to do |format|
      format.js
    end
  end

  def destroy
    PreferenceList.find(params[:id]).delete
    respond_to do |format|
      format.js
    end
  end

  private
  def create_preference_list
    if !current_renter.preference_list
      preference_list = PreferenceList.new()
      preference_list.renter = current_renter
      current_renter.preference_list = preference_list
      preference_list.save
      current_renter.save
    end
  end

  def get_selected_amenities(preference_list)
    amenities_list = []
    amenities_list << 'Reception' if preference_list.reception == true
    amenities_list << 'Light' if preference_list.light == true
    amenities_list << 'Shower' if preference_list.shower == true
    amenities_list << 'Move_in' if preference_list.move_in == true
    amenities_list << 'High_ceiling' if preference_list.high_ceiling == true
    amenities_list << 'Patio' if preference_list.patio == true
    amenities_list << 'Furniture' if preference_list.furniture == true
    amenities_list
  end
end

app/views/preference_lists/add_amenity.js.erb
<% unless @amenity == "" %>
  var amenity_name = $('<div class="amenity-name"><%= @amenity %> <%= link_to "&#215".html_safe, preference_list_remove_amenity_path(renter_id: current_renter.id, amenity: @amenity), remote: true, method: "patch", class: "remove-preference" %></div>');
  $('.amenities-names').append(amenity_name);
<% end %>

app/views/preference_lists/add_broker.js.erb
<% unless @broker == "" %>
  var broker_email = $('<div class="broker-name"><%= @broker.email %> <%= link_to "&#215".html_safe, preference_list_remove_broker_path(renter_id: current_renter.id, broker_id: @broker.id), remote: true, method: "patch", class: "remove-preference" %></div>')
  $('.brokers-names').append(broker_email);
<% end %>

app/views/preference_lists/add_neighborhood.js.erb
<% unless @neighborhood == "" %>
  var neighborhood_name = $('<div class="neighborhood-name"><%= @neighborhood.name %> <%= link_to "&#215".html_safe, preference_list_remove_neighborhood_path(renter_id: current_renter.id, neighborhood_id: @neighborhood.id), remote: true, method: "patch", class: "remove-preference" %></div>')
  $('.neighborhoods-names').append(neighborhood_name);
<% end %>

app/views/preference_lists/create.js.erb
console.log("Hello tanay")
$('#enable-preference-list-button').addClass('hidden');
$('#disable-preference-list-button').removeClass('hidden');

app/views/preference_lists/destroy.js.erb
console.log("hello tanay");
$('#enable-preference-list-button').removeClass('hidden');
$('#disable-preference-list-button').addClass('hidden');

app/views/preference_lists/edit.html.haml
.row
  .title-container.small-10.columns.small-centered
    Edit Notification Preferences

.row
  .small-4.columns.small-centered
.row
  .small-4.columns
    .neighborhoods-container
      .neighborhoods-title
        Notify Me of New Postings in these Neighborhoods:
      .neighborhoods-names
        -@renter_neighborhoods.each do |neighborhood|
          .neighborhood-name 
            =neighborhood.name
            =link_to "&#215".html_safe, preference_list_remove_neighborhood_path(renter_id: current_renter.id, neighborhood_id: neighborhood.id), remote: true, method: "patch", class: "remove-preference"
  .small-4.columns
    .brokers-container
      .brokers-title
        Notify Me of New Postings by these Brokers:
      .brokers-names
        -@renter_brokers.each do |broker|
          .broker-name 
            =broker.email
            =link_to "&#215".html_safe, preference_list_remove_broker_path(renter_id: current_renter.id, broker_id: broker.id), remote: true, method: "patch", class: "remove-preference"
  .small-4.columns
    .amenities-container
      .amenities-title
        Notify Me of Offices Only if They Have these Amenities:
      .amenities-names
        -@renter_amenities.each do |amenity|
          .amenity-name 
            =amenity
            =link_to "&#215".html_safe, preference_list_remove_amenity_path(renter_id: current_renter.id, amenity: amenity), remote: true, method: "patch", class: "remove-preference"

.row
  .small-4.columns
    .neighborhoods-select-container
      = form_tag preference_list_add_neighborhood_path(renter_id: current_renter.id), method: "patch", remote: true  do
        = select_tag nil, options_for_select(@all_neighborhoods.collect { |neighborhood| [neighborhood.name, neighborhood.id]}), id: 'neighborhoods-select', name: "neighborhood_id"
        = submit_tag "Add Neighborhood", class: "small button", id: "purple-button"
  .small-4.columns
    .brokers-select-container
      = form_tag preference_list_add_broker_path(renter_id: current_renter.id), method: "patch", remote: true  do
        = select_tag nil, options_for_select(@all_brokers.collect { |broker| [broker.email, broker.id]}), id: 'brokers-select', name: "broker_id"
        = submit_tag "Add Broker", class: "small button", id: "purple-button"
  .small-4.columns
    .amenities-select-container
      = form_tag preference_list_add_amenity_path(renter_id: current_renter.id), method: "patch", remote: true  do
        = select_tag nil, options_for_select(@all_amenities.collect { |amenity| [amenity, amenity]}), id: 'amenities-select', name: "amenity"
        = submit_tag "Add Amenity", class: "small button", id: "purple-button"

app/views/preference_lists/remove_amenity.js.erb
$(".amenity-name:contains('<%= @amenity %>')").first().remove();

app/views/preference_lists/remove_broker.js.erb
$(".broker-name:contains('<%= @broker.email %>')").first().remove();

app/views/preference_lists/remove_neighborhood.js.erb
$(".neighborhood-name:contains('<%= @neighborhood.name %>')").first().remove();